// <auto-generated />
using System;
using EasyStock.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EasyStock.Sprint3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260322161617_InitialSprint2")]
    partial class InitialSprint2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EasyStock.Models.Affectation", b =>
                {
                    b.Property<int>("AffectationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AffectationId"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EtatRetour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EtatSortie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ReferenceCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AffectationId");

                    b.HasIndex("ArticleId");

                    b.HasIndex("ReferenceCode")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Affectation");
                });

            modelBuilder.Entity("EasyStock.Models.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArticleId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FournisseurId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NombreArticleActuel")
                        .HasColumnType("int");

                    b.Property<int>("NombreArticleMinimum")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArticleId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FournisseurId");

                    b.ToTable("Article");

                    b.HasData(
                        new
                        {
                            ArticleId = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Description = "Portable equipe finance",
                            FournisseurId = 3,
                            Name = "Latitude 5540 - i7/16Go/512Go",
                            NombreArticleActuel = 14,
                            NombreArticleMinimum = 5,
                            UpdatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        },
                        new
                        {
                            ArticleId = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Description = "Portable standard equipe operations",
                            FournisseurId = 8,
                            Name = "ThinkPad T14 Gen 4",
                            NombreArticleActuel = 11,
                            NombreArticleMinimum = 4,
                            UpdatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        },
                        new
                        {
                            ArticleId = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Description = "Poste fixe reception",
                            FournisseurId = 3,
                            Name = "OptiPlex 7010 SFF",
                            NombreArticleActuel = 6,
                            NombreArticleMinimum = 2,
                            UpdatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        },
                        new
                        {
                            ArticleId = 4,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Description = "Poste fixe comptabilite",
                            FournisseurId = 4,
                            Name = "EliteDesk 800 G9",
                            NombreArticleActuel = 5,
                            NombreArticleMinimum = 2,
                            UpdatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        },
                        new
                        {
                            ArticleId = 5,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Description = "Switch coeur PME 24 ports PoE",
                            FournisseurId = 5,
                            Name = "Cisco Catalyst C9200L-24P",
                            NombreArticleActuel = 3,
                            NombreArticleMinimum = 1,
                            UpdatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        },
                        new
                        {
                            ArticleId = 6,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Description = "Point d'acces wifi bureaux",
                            FournisseurId = 2,
                            Name = "Ubiquiti UniFi U6-LR",
                            NombreArticleActuel = 12,
                            NombreArticleMinimum = 4,
                            UpdatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        },
                        new
                        {
                            ArticleId = 7,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Description = "Pare-feu principal site",
                            FournisseurId = 6,
                            Name = "Firewall FortiGate 60F",
                            NombreArticleActuel = 2,
                            NombreArticleMinimum = 1,
                            UpdatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        },
                        new
                        {
                            ArticleId = 8,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Description = "NAS sauvegarde departement",
                            FournisseurId = 1,
                            Name = "Synology DS923+ NAS",
                            NombreArticleActuel = 4,
                            NombreArticleMinimum = 2,
                            UpdatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        },
                        new
                        {
                            ArticleId = 9,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Description = "Disque pour NAS RAID",
                            FournisseurId = 1,
                            Name = "Disque WD Red 8To",
                            NombreArticleActuel = 18,
                            NombreArticleMinimum = 6,
                            UpdatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        },
                        new
                        {
                            ArticleId = 10,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Description = "Piece de rechange portable",
                            FournisseurId = 2,
                            Name = "SSD NVMe 1To Samsung 990",
                            NombreArticleActuel = 20,
                            NombreArticleMinimum = 8,
                            UpdatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        },
                        new
                        {
                            ArticleId = 11,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Description = "Moniteur 24 pouces bureau",
                            FournisseurId = 3,
                            Name = "Ecran Dell P2422H",
                            NombreArticleActuel = 26,
                            NombreArticleMinimum = 10,
                            UpdatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        },
                        new
                        {
                            ArticleId = 12,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Description = "Dock USB-C/TB pour portables",
                            FournisseurId = 3,
                            Name = "Station d'accueil Dell WD22TB4",
                            NombreArticleActuel = 13,
                            NombreArticleMinimum = 5,
                            UpdatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        },
                        new
                        {
                            ArticleId = 13,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Description = "Clavier bureautique USB",
                            FournisseurId = 7,
                            Name = "Clavier Logitech K280e",
                            NombreArticleActuel = 44,
                            NombreArticleMinimum = 15,
                            UpdatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        },
                        new
                        {
                            ArticleId = 14,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Description = "Souris filaire bureautique",
                            FournisseurId = 7,
                            Name = "Souris Logitech M500s",
                            NombreArticleActuel = 39,
                            NombreArticleMinimum = 12,
                            UpdatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        },
                        new
                        {
                            ArticleId = 15,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Description = "Casque calls equipe service client",
                            FournisseurId = 6,
                            Name = "Casque Jabra Evolve2 40",
                            NombreArticleActuel = 17,
                            NombreArticleMinimum = 6,
                            UpdatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        },
                        new
                        {
                            ArticleId = 16,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Description = "Controle acces entree principale",
                            FournisseurId = 6,
                            Name = "Lecteur badge HID Signo 20",
                            NombreArticleActuel = 7,
                            NombreArticleMinimum = 3,
                            UpdatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        },
                        new
                        {
                            ArticleId = 17,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Description = "Protection electrique salle serveur",
                            FournisseurId = 1,
                            Name = "Onduleur APC Smart-UPS 1500",
                            NombreArticleActuel = 4,
                            NombreArticleMinimum = 2,
                            UpdatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        },
                        new
                        {
                            ArticleId = 18,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Description = "Imprimante multifonction RH",
                            FournisseurId = 4,
                            Name = "HP LaserJet Pro MFP 4101",
                            NombreArticleActuel = 3,
                            NombreArticleMinimum = 1,
                            UpdatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        },
                        new
                        {
                            ArticleId = 19,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Description = "Imprimante volume eleve",
                            FournisseurId = 2,
                            Name = "Brother HL-L6400DW",
                            NombreArticleActuel = 2,
                            NombreArticleMinimum = 1,
                            UpdatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        },
                        new
                        {
                            ArticleId = 20,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Description = "Consommable imprimante HP",
                            FournisseurId = 7,
                            Name = "Cartouche toner HP 89X",
                            NombreArticleActuel = 28,
                            NombreArticleMinimum = 10,
                            UpdatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        },
                        new
                        {
                            ArticleId = 21,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Description = "Webcam salle et teletravail",
                            FournisseurId = 6,
                            Name = "Webcam Logitech Brio",
                            NombreArticleActuel = 9,
                            NombreArticleMinimum = 3,
                            UpdatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        },
                        new
                        {
                            ArticleId = 22,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Description = "Barre video salle reunion",
                            FournisseurId = 6,
                            Name = "Poly Studio USB",
                            NombreArticleActuel = 3,
                            NombreArticleMinimum = 1,
                            UpdatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        },
                        new
                        {
                            ArticleId = 23,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Description = "Affichage principal salle B",
                            FournisseurId = 2,
                            Name = "TV Samsung 65 pouces 4K",
                            NombreArticleActuel = 2,
                            NombreArticleMinimum = 1,
                            UpdatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        },
                        new
                        {
                            ArticleId = 24,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Description = "Patch cord postes et baies",
                            FournisseurId = 7,
                            Name = "Cable reseau Cat6 2m",
                            NombreArticleActuel = 120,
                            NombreArticleMinimum = 40,
                            UpdatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        },
                        new
                        {
                            ArticleId = 25,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Description = "Adaptateur reseau pour portables",
                            FournisseurId = 2,
                            Name = "Adaptateur USB-C vers RJ45",
                            NombreArticleActuel = 31,
                            NombreArticleMinimum = 12,
                            UpdatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        });
                });

            modelBuilder.Entity("EasyStock.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Name = "Postes de travail",
                            UpdatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        },
                        new
                        {
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Name = "Infrastructure reseau",
                            UpdatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        },
                        new
                        {
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Name = "Stockage et sauvegarde",
                            UpdatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        },
                        new
                        {
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Name = "Peripheriques utilisateur",
                            UpdatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        },
                        new
                        {
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Name = "Securite et acces",
                            UpdatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        },
                        new
                        {
                            CategoryId = 6,
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Name = "Impression et numerisation",
                            UpdatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        },
                        new
                        {
                            CategoryId = 7,
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Name = "Salles de reunion",
                            UpdatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        },
                        new
                        {
                            CategoryId = 8,
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Name = "Consommables et pieces",
                            UpdatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        });
                });

            modelBuilder.Entity("EasyStock.Models.Fournisseur", b =>
                {
                    b.Property<int>("FournisseurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FournisseurId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FournisseurId");

                    b.ToTable("Fournisseur");

                    b.HasData(
                        new
                        {
                            FournisseurId = 1,
                            Address = "16711 Transcanada Hwy, Kirkland, QC",
                            ContactEmail = "commandes@ingrammicro.ca",
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nom = "Ingram Micro Canada",
                            PhoneNumber = "514-555-0101",
                            UpdatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        },
                        new
                        {
                            FournisseurId = 2,
                            Address = "200 Wellington St W, Toronto, ON",
                            ContactEmail = "ventes@cdw.ca",
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nom = "CDW Canada",
                            PhoneNumber = "416-555-0102",
                            UpdatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        },
                        new
                        {
                            FournisseurId = 3,
                            Address = "155 Gordon Baker Rd, Toronto, ON",
                            ContactEmail = "pmecanada@dell.com",
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nom = "Dell Technologies",
                            PhoneNumber = "800-555-0103",
                            UpdatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        },
                        new
                        {
                            FournisseurId = 4,
                            Address = "1000 De La Gauchetiere O, Montreal, QC",
                            ContactEmail = "comptes@hp.com",
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nom = "HP Entreprise",
                            PhoneNumber = "514-555-0104",
                            UpdatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        },
                        new
                        {
                            FournisseurId = 5,
                            Address = "4500 Boul. Matte, Brossard, QC",
                            ContactEmail = "reseau@ciscopartner.ca",
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nom = "Cisco Partner Quebec",
                            PhoneNumber = "450-555-0105",
                            UpdatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        },
                        new
                        {
                            FournisseurId = 6,
                            Address = "173 Dufferin St, Toronto, ON",
                            ContactEmail = "appro@softchoice.com",
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nom = "SoftChoice",
                            PhoneNumber = "416-555-0106",
                            UpdatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        },
                        new
                        {
                            FournisseurId = 7,
                            Address = "5500 Explorer Dr, Mississauga, ON",
                            ContactEmail = "b2b@staples.ca",
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nom = "Staples Professionnel",
                            PhoneNumber = "877-555-0107",
                            UpdatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        },
                        new
                        {
                            FournisseurId = 8,
                            Address = "151 Yonge St, Toronto, ON",
                            ContactEmail = "proaccounts@lenovo.ca",
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nom = "Lenovo Canada",
                            PhoneNumber = "866-555-0108",
                            UpdatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        });
                });

            modelBuilder.Entity("EasyStock.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Description = "Accès complet à l'application",
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            Description = "Gestion des opérations et consultation des utilisateurs",
                            RoleName = "Gestionnaire"
                        },
                        new
                        {
                            RoleId = 3,
                            Description = "Gestion opérationnelle de l'inventaire et des affectations",
                            RoleName = "Operateur"
                        });
                });

            modelBuilder.Entity("EasyStock.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PwdHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Email = "admin@easystock.local",
                            PwdHash = "3EB3FE66B31E3B4D10FA70B5CAD49C7112294AF6AE4E476A1C405155D45AA121",
                            RoleId = 1,
                            UpdatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "system",
                            Username = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Email = "gestionnaire@easystock.local",
                            PwdHash = "14CB1392E34869C5AD54C212F8D4DB51C78A851675E5F4CDED2C550A5FC92792",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "system",
                            Username = "gestionnaire"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "system",
                            Email = "operateur@easystock.local",
                            PwdHash = "C92285D3BAA1271D81C07697A2E39986146D05563EF07ECBD7E291E57420BF10",
                            RoleId = 3,
                            UpdatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "system",
                            Username = "operateur"
                        });
                });

            modelBuilder.Entity("EasyStock.Models.Affectation", b =>
                {
                    b.HasOne("EasyStock.Models.Article", "Article")
                        .WithMany("Affectations")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EasyStock.Models.User", "User")
                        .WithMany("Affectations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EasyStock.Models.Article", b =>
                {
                    b.HasOne("EasyStock.Models.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EasyStock.Models.Fournisseur", "Fournisseur")
                        .WithMany("Articles")
                        .HasForeignKey("FournisseurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Fournisseur");
                });

            modelBuilder.Entity("EasyStock.Models.User", b =>
                {
                    b.HasOne("EasyStock.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EasyStock.Models.Article", b =>
                {
                    b.Navigation("Affectations");
                });

            modelBuilder.Entity("EasyStock.Models.Category", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("EasyStock.Models.Fournisseur", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("EasyStock.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("EasyStock.Models.User", b =>
                {
                    b.Navigation("Affectations");
                });
#pragma warning restore 612, 618
        }
    }
}
